module.exports = {
    //Question difficuly level constant
    QUESTION_LEVEL_HIGH: "HIGH",
    QUESTION_LEVEL_MODERATE: "MODERATE",
    QUESTION_LEVEL_EASY: "EASY",

    //constants used for mongoose model mapping
    MODEL_MASTERDATA: "MASTERDATA",
    MODEL_CLIENT: "CLIENT",
    MODEL_USER: "USER",
    MODEL_QUESTION: "QUESTION",
    MODEL_QUESTIONNAIRE: "QUESTIONNAIRE",
    MODEL_SEQUENCE: "MODELSEQUENCE",
    MODEL_CANDIDATE: "MODELCANDIDATE",
    MODEL_CANDIDATE_GROUP: "MODELCANDIDATEGROUP",
    MODEL_CLIENT_IMAGE: "CLIENTIMAGE",
    MODEL_CANDIDATE_EXAM: "MODELCANDIDATEEXAM",
    MODEL_EXAM_CANDIDATE_DATA:"MODELEXAMCANDIDATEDATA",
    MODEL_EXAM_QUES_DATA:"MODELEXAMQUESDATA",
    //constants for Services
    SERVICE_USER: "USERSERVICE",
    SERVICE_CLIENT: "CLIENTSERVICE",
    SERVICE_EMAIL: "EMAILSERVICE",
    SERVICE_AUTHENTICATION: "AUTHENTICATIONSERVICE",
    SERVICE_QUESTIONNAIRE: "QUESTIONNAIRESERVICE",
    SERVICE_QUESTION: "QUESTIONSERVICE",
    SERVICE_CANDIDATE: "CANDIDATESERVICE",
    SERVICE_MASTERDATA: "MASTERDATASERVICE",
    SERVICE_UTIL: "UTILSERVICE",
    SERVICE_CANDIDATE_EXAM: "CANDIDATEEXAMSERVICE",
    SERVICE_EXAM_CANDIDATE_DATA: "EXAMCANDIDATEDATASERVICE",
    SERVICE_EXAM_QUES_DATA: "EXAMQUESDATASERVICE",
    //constant for dao
    DAO_CLIENT: "CLIENTDAO",
    DAO_USER: "USERDAO",
    DAO_QUESTION: "QUESTIONDAO",
    DAO_QUESTIONNAIRE: "QUESTIONNAIREDAO",
    DAO_MASTERDATA: "MASTERDATADAO",
    DAO_CANDIDATE: "CANDIDATEDAO",
    DAO_CANDIDATE_EXAM: "CANDIDATEEXAMDAO",
    DAO_EXAM_CANDIDATE_DATA: "EXAMCANDIDATEDATADAO",
    DAO_EXAM_QUES_DATA: "EXAMQUESDATADAO",
    DAO_UTIL: "UTILDAO",
    //constants for mappings
    MAPPING_USER: "USER",

    //constants for validation type
    CLIENT_VALIDATION: "CLIENT_VALIDATION",
    USER_VALIDATION: "USER_VALIDATION",
    QUESTIONNAIRE_VALIDATION: "QUESTIONNAIRE_VALIDATION",
    CANDIDATE_VALIDATION: "CANDIDATE_VALIDATION",
    //constants for operations
    SIGN_UP: "SIGN_UP",
    LOGIN: "LOGIN",
    SAVE_QUESTIONNAIRE: "SAVE_QUESTIONNAIRE",
    SAVE_QUESTION: "SAVE_QUESTION",
    SAVE_CANDIDATE: "SAVE_CANDIDATE",
    UPDATE_CANDIDATE: "UPDATE_CANDIDATE",
    BULK_CANDIDATE_UPLOAD: "BULK_CANDIDATE_UPLOAD",
    //constants for questionnaire status
    DRAFT: "Draft",
    FINALISED: "Finalised",
    INACTIVE: "Inactive",

    // master data constants

    SECTION: "SECTION",
    CATEGORY: "CATEGORY",
    SUBJECT: "SUBJECT",
    EXAM_DURATION: "EXAM_DURATION",
    EXAM_AVAILABILITY: "EXAM_AVAILABILITY",
    RESULT_TYPE: "RESULT_TYPE",
    ORDER_OF_QUES: "ORDER_OF_QUES",
    RESULT_REPORT_TYPE: "RESULT_REPORT_TYPE",
    SCORING: "SCORING",
    MINIMUM_PASSING_SCORE: "MINIMUM_PASSING_SCORE"
}