module.exports = {
    //constants for error codes
    DUP_USER: "DUPLICATE_USER",
    DUP_EMAIL: "DUPLICATE_EMAIL",
    NO_PASSWORD: "PASSWORD_MISSING",
    NO_USER_NAME: "USER_NAME_MISSING",
    INVALID_PASS_FORMAT: "INVALID_PASSWORD_FORMAT",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    NO_ORGANISATION: "ORGANISATION_MISSING",
    NO_EMAIL_ID: "EMAILID_MISSING",
    NO_CONTACT_NO: "CONTACT_NO_MISSING",
    NO_CONTACT_NAME: "CONTACT_NAME_MISSING",

    NO_QUESTIONNAIRE_FOUND: "NO_QUESTIONNAIRE_FOUND",

    //login error constants
    NO_USER_FOUND: "NO_USER_FOUND",
    INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
    USER_INACTIVE: "USER_INACTIVE",


    //constants for error types
    VALIDATION_ERROR: "VALIDATION_ERROR"
}