module.exports = {
    //constants for error codes
    DUP_USER: "DUPLICATE_USER",
    DUP_CLIENT_EMAIL: "DUPLICATE_CLIENT_EMAIL",
    DUP_USER_EMAIL: "DUPLICATE_USER_EMAIL",
    NO_PASSWORD: "PASSWORD_MISSING",
    NO_USER_NAME: "USER_NAME_MISSING",
    NO_CLIENT_CODE: "CLIENT_CODE_MISSING",
    INVALID_PASS_FORMAT: "INVALID_PASSWORD_FORMAT",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    NO_ORGANISATION: "ORGANISATION_MISSING",
    NO_EMAIL_ID: "EMAILID_MISSING",
    NO_CONTACT_NO: "CONTACT_NO_MISSING",
    NO_CONTACT_NAME: "CONTACT_NAME_MISSING",
    NO_USER_EMAIL_ID_FOUND: "NO_USER_EMAIL_ID_FOUND",
    NO_CLIENT_EMAIL_ID_FOUND: "NO_CLIENT_EMAIL_ID_FOUND",
    NO_CLIENT_FOUND: "NO_CLIENT_FOUND",

    NO_QUESTIONNAIRE_FOUND: "NO_QUESTIONNAIRE_FOUND",
    NO_QUESTION_FOUND: "NO_QUESTION_FOUND",

    //candidate error codes
    NO_CANDIDATE_FOUND: "NO_CANDIDATE_FOUND",
    //login error constants
    NO_USER_FOUND: "NO_USER_FOUND",
    INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
    USER_INACTIVE: "USER_INACTIVE",

    //question and questionnaire error constants
    NO_TITLE: "TITLE_MISSING",
    NO_MARKS: "MARKS_MISSING",
    NO_DURATION: "DURATION_MISSING",
    NO_NUM_OF_QUES: "NUM_OF_QUES_MISSING",
    NO_QUESTIONNAIRE_FOUND: "NO_QUESTIONNAIRE_FOUND",

    NO_QUESTION_TITLE: "QUESTION_TITLE_MISSING",
    NO_QUESTION_TYPE: "QUESTION_TYPE_MISSING",
    INVALID_QUESTION_TYPE: "INVALID_QUESTION_TYPE",


    //constants for error types
    SIGN_UP_VALIDATION_ERROR: "SIGN_UP_VALIDATION_ERROR",
    LOGIN_VALIDATION_ERROR: "LOGIN_VALIDATION_ERROR",
    QUESTIONNAIRE_VALIDATION_ERROR: "QUESTIONNAIRE_VALIDATION_ERROR"
}