module.exports = {
    //constants for error codes
    DUP_USER: "DUP_USER",
    DUP_EMAIL: "DUP_EMAIL",
    WRNG_PASS: "WRNG_PASS",
    NO_PASSWORD: "NO_PASSWORD",
    NO_USER_NAME: "NO_USER_NAME",
    INVALID_PASS_FORMAT: "INVALID_PASS_FORMAT",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    NO_ORGANISATION:"NO_ORGANISATION",
    NO_EMAILID:"NO_EMAILID",
    NO_CONTACT_NO:"NO_CONTACT_NO",
    NO_CONTACT_NAME:"NO_CONTACT_NAME",

NO_QUESTIONNAIRE_FOUND: "NO_QUESTIONNAIRE_FOUND",

    //login error constants
    NO_USER_FOUND:"NO_USER_FOUND",
    INVALID_CREDENTIAL:"INVALID_CREDENTIAL",
    USER_INACTIVE:"USER_INACTIVE",


    //constants for error types
    VALIDATION_ERROR: "VALIDATION_ERROR"
}